USE lab_mysql;

# Car table
CREATE TABLE Cars(
CAR_ID INT AUTO_INCREMENT PRIMARY KEY,
VIN VARCHAR(50) NOT NULL,
Manufacturer VARCHAR(50) NOT NULL,
Model VARCHAR(50) NOT NULL,
Year YEAR NOT NULL,
Color VARCHAR(50) NOT NULL)

# Customers table
CREATE TABLE Customers(
Customer_ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Phone VARCHAR(50) NOT NULL,
Email VARCHAR(50),
Address	VARCHAR(50) NOT NULL,
City VARCHAR(50) NOT NULL,
State_Province VARCHAR(50) NOT NULL,
Country VARCHAR(50) NOT NULL,
Postal INT NOT NULL)

# Salespersons table
CREATE TABLE Salespersons(
Staff_ID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
Store VARCHAR(50) NOT NULL)

# Invoices table
CREATE TABLE Invoices(
Invoice_ID INT AUTO_INCREMENT PRIMARY KEY,
Invoice_Number VARCHAR(50) NOT NULL,
Date DATE NOT NULL,
Car INT NOT NULL,
Customer INT NOT NULL,
Salesperson INT NOT NULL)
